### DISCUSSION TITLE
Support request: MallocStackLogging: can't turn off malloc stack logging because it was not enabled

### DISCUSSION THREAD

**Discussion by dmorand17** [aws/amazon-q-developer-cli#205] [Q&A]
### Checks

- [X] I ran `cw doctor` in the affected command line session and it didn't resolve my issue
- [X] I ran `cw restart` and it didn't resolve my issue
- [X] I searched [the discussions in this repo](https://github.com/aws/codewhisperer-command-line-discussions/discussions?q=) and there are no duplicates of my issue

### Expected behaviour

I am using autocomplete for aws commands (i.e. `aws cloudformation `) and sporadically receive errors about **MallocStackLogging**

### Actual behaviour

When using cw in ZSH I'm getting sporadic issues where autocomplete fails with the following error.

```
MallocStackLogging: can't turn off malloc stack logging because it was not enabled
```

### Environment

```yaml
CODEWHISPERER-details:
  - 0.14.1
hardware-info:
  - model: 
  - model-id: 
  - chip-id: Apple M1
  - cores: 8
  - mem: 16.00 GB
os-info:
  - macOS 14.3.1 (23D60)
environment:
  - shell: /bin/zsh
  - terminal: vscode
  - cwd: /Users/domorand/workspace/work/_research-computing/open-on-demand-on-aws
  - exe-path: /Users/domorand/.local/bin/cw
  - install-method: unknown
  - env-vars:
    - CWTERM_SESSION_ID: 8fdd2794947248378c13baf3d2793a33
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.14.1
    - PATH: /Users/domorand/.local/bin:/opt/homebrew/bin:/opt/homebrew/opt/gnu-sed/libexec/gnubin:/opt/homebrew/opt/coreutils/libexec/gnubin:/Users/domorand/.nvm/versions/node/v20.11.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/domorand/.zplug/repos/zplug/zplug/bin:/Users/domorand/.zplug/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/domorand/.cargo/bin:/Users/domorand/.local/bin:/opt/homebrew/opt/fzf/bin:/Users/domorand/workspace/personal/scripts/aws/lambda:/Users/domorand/workspace/automated-security-helper:/Users/domorand/workspace/personal/scripts/aws/iam:/Users/domorand/.guard/bin
    - SHELL: /bin/zsh
    - TERM: xterm-256color
    - ZDOTDIR: /Users/domorand
    - __CFBundleIdentifier: com.microsoft.VSCode
    - CW_SET_PARENT: 8fdd2794947248378c13baf3d2793a33
```

**Comment by wang-zhenqi** [comment]
I ran into this issue too. Done the `cw doctor` and `cw restart`, but the message keeps showing up.

### Environment

```
CODEWHISPERER-details:
  - 0.15.1
hardware-info:
  - model:
  - model-id:
  - chip-id: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  - cores: 6
  - mem: 16.00 GB
os-info:
  - macOS 14.4.0 (23E214)
environment:
  - shell: /bin/zsh
  - terminal: iterm
  - cwd: /Users/zhenqi.wang
  - exe-path: /Users/zhenqi.wang/.local/bin/cw
  - install-method: brew
  - env-vars:
    - CWTERM_SESSION_ID: 0549bbbf484e4ca197936ca63c7fd3a5
    - CW_SET_PARENT_CHECK: 1
    - CW_TERM: 0.15.1
    - DISPLAY: /private/tmp/com.apple.launchd.YXHgKkDVUX/org.xquartz:0
    - PATH: /Users/zhenqi.wang/opt/anaconda3/bin:/Users/zhenqi.wang/.asdf/shims:/usr/local/opt/asdf/libexec/bin:/Users/zhenqi.wang/opt/anaconda3/bin:/Users/zhenqi.wang/.sdkman/candidates/java/current/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/TeX/texbin:/usr/local/munki:/Users/zhenqi.wang/.local/bin
    - SHELL: /bin/zsh
    - TERM: linux
    - __CFBundleIdentifier: com.googlecode.iterm2
    - CW_SET_PARENT: 0549bbbf484e4ca197936ca63c7fd3a5

```
